"""Locked public audio-window timing shared across pipeline layers."""

SAMPLE_RATE_HZ = 48_000
DECISION_HOP_SAMPLES = 960
DOA_WINDOW_SAMPLES = 1_920
CONTEXT_SAMPLES = 7_680
CONTEXT_HOPS = CONTEXT_SAMPLES // DECISION_HOP_SAMPLES
STFT_FRAME_COUNT = 1 + CONTEXT_SAMPLES // 480
